# -*- coding: utf-8 -*-
"""Doc genie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tn6IAFMOSyWRAJ3t3-KzXZdFh2Gj5jRe
"""

!pip install gradio==4.41.0
!pip install transformers==4.35.0
!pip install torch==2.0.0
!pip install reportlab==4.0.7
!pip install requests==2.31.0
!pip install black==24.1.1
!pip install autopep8==2.1.0

import ast
import gradio as gr
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
import datetime

class DocGenieAnalyzer:

    @staticmethod
    def extract_function_signature(code):
        tree = ast.parse(code)
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                name = node.name
                params = [arg.arg for arg in node.args.args]
                return {"name": name, "params": params}
        return {}

    @staticmethod
    def generate_google_docstring(signature):
        name = signature.get("name", "")
        params = signature.get("params", [])

        doc = f'"""{name} function.\n\nArgs:\n'
        for p in params:
            doc += f"    {p}: description\n"
        doc += "\nReturns:\n    result\n\"\"\""

        return doc

def generate_docstring(code):

    sig = DocGenieAnalyzer.extract_function_signature(code)

    if not sig:
        return "No function found"

    doc = DocGenieAnalyzer.generate_google_docstring(sig)

    return code.replace(":", ":\n    " + doc)

interface = gr.Interface(
    fn=generate_docstring,
    inputs=gr.Textbox(lines=10, label="Enter Python Code"),
    outputs=gr.Textbox(lines=15, label="Generated Code with Docstring"),
    title="Doc Genie",
    description="Python Function Docstring Generator"
)

interface.launch()